Use MatrixError
matrix-org/matrix-appservice-bridge pull request #441
Opened 2022-10-05 16:05 UTC by Half-Shot

Successor to #360, but more up to date

2022-10-05 16:36 UTC, jaller94 approved these changes
Looks good.

2022-10-05 16:36 UTC, jaller94 commented on src/components/room-upgrade-handler.ts
> +            console.log("THE EX", ex);
This was left from debugging, I guess?.
Otherwise, using a `log` library and a proper description would be much appreciated. :)
```suggestion
```

2022-10-05 16:36 UTC, jaller94 commented on spec/unit/intent.spec.js
> +const matrixError = async (errcode, error) => { throw new MatrixError({errcode, error}, 500)};
When to use the second parameter of `MatrixError.constructor` and when not?

2022-10-06 09:41 UTC, Half-Shot commented on src/components/room-upgrade-handler.ts
> +            console.log("THE EX", ex);
Definitely debugging. Definitely not helpful to anyone else :)

2022-10-06 16:17 UTC, Half-Shot commented on spec/unit/intent.spec.js
> +const matrixError = async (errcode, error) => { throw new MatrixError({errcode, error}, 500)};
Always really, this is just laziness...

2022-10-25 19:10 UTC, AndrewFerr commented
Turning on `useUnknownInCatchVariables` in the tsconfig exposes some more places where `MatrixError` can/should be used instead.  I'll get on it because the lack of typed errors has been bugging me more and more lately & I'd love to have it in.

2022-10-25 19:31 UTC, AndrewFerr requested changes, later dismissed
I'll see how far I can get with enforcing `useUnknownInCatchVariables`.

2022-10-25 19:31 UTC, AndrewFerr commented on src/components/membership-queue.ts
> +        return false;
Should this return `true` instead?  If `ex` isn't a `MatrixError`, the original code can resolve to `!(undefined === <something>)` -> `!false` -> `true`

2022-10-25 19:31 UTC, AndrewFerr commented on src/components/stores/event-store.ts
> -import { StoredEvent } from "../../models/events/event";
I may rebase this PR to split out these file removals (which have since been committed as 7018468).

2022-11-03 20:47 UTC, merged